apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parrot.fullname" . }}
  labels:
    {{- include "parrot.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.config | b64enc }}
  