swagger: "2.0"
info:
  description: POEditor pull through cache
  title: Parrot
  version: 1.0.0
produces:
  - application/json
schemes:
  - https
paths:
  /v1/project/{project}/language/{language}:
    parameters:
      - type: integer
        format: int32
        description: Project id in POEditor
        name: project
        in: path
        required: true
      - type: string
        description: Language code
        name: language
        in: path
        required: true
    get:
      responses:
        "200":
          description: "Successful"
        "400":
          description: "Invalid project id"
        "404":
          description: "No translation found for language code"
  /v1/project/{project}/purge:
    parameters:
      - type: integer
        format: int32
        description: Project id in POEditor
        name: project
        in: path
        required: true
    post:
      responses:
        "200":
          description: "Successful"
        "400":
          description: "Invalid project id"
  /v1/project/{project}/language/{language}/purge:
    parameters:
      - type: integer
        format: int32
        description: Project id in POEditor
        name: project
        in: path
        required: true
      - type: string
        description: Language code
        name: language
        in: path
        required: true
    post:
      responses:
        "200":
          description: "Successful"
        "400":
          description: "Invalid project id"
