swagger: '2.0'
info:
  description: POEditor pull through cache
  title: Parrot
  version: 1.0.0
produces:
  - application/json
schemes:
  - https
paths:
  /v1/project/{project}/language/{language}:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful"
        "400":
          description: "Invalid project id"
        "404":
          description: "No translation found for language code"