openapi: "3.0.0"

info:
  title: Parrot
  version: 1.0.0
  description: POEditor pull through cache

servers:
  - url: https://api.eu.wiseflow.io/i18n
    description: Production
  - url: https://api.stage.eu.wiseflow.io/i18n
    description: Staging
  - url: https://api.test.eu.wiseflow.io/i18n
    description: Testing
  - url: "{scheme}://{host}{base}"
    description: Custom
    variables:
      scheme:
        default: "http"
        enum:
          - "http"
          - "https"
      host:
        default: "localhost:8080"
      base:
        default: ""

paths:
  /v1/project/{project}/language/{language}:
    parameters:
      - schema:
          type: integer
          format: int32
        description: Project id in POEditor
        name: project
        in: path
        required: true
      - schema:
          type: string
        description: Language code
        name: language
        in: path
        required: true
      - schema:
          type: string
          enum:
            - po
            - pot
            - mo
            - xls
            - xlsx
            - csv
            - ini
            - resw
            - resx
            - android_strings
            - apple_strings
            - xliff
            - properties
            - key_value_json
            - json
            - yml
            - xlf
            - xmb
            - xtb
            - arb
            - rise_360_xliff
        description: The format of the return data
        name: format
        in: query
        required: false
    get:
      tags:
        - project
      responses:
        "200":
          description: "Successful"
        "400":
          description: "Invalid project id"
        "404":
          description: "No translation found for language code"
  /v1/project/{project}/purge:
    parameters:
      - schema:
          type: integer
          format: int32
        description: Project id in POEditor
        name: project
        in: path
        required: true
    post:
      tags:
        - project
      responses:
        "200":
          description: "Successful"
        "400":
          description: "Invalid project id"
  /v1/project/{project}/language/{language}/purge:
    parameters:
      - schema:
          type: integer
          format: int32
        description: Project id in POEditor
        name: project
        in: path
        required: true
      - schema:
          type: string
        description: Language code
        name: language
        in: path
        required: true
    post:
      tags:
        - project
      responses:
        "200":
          description: "Successful"
        "400":
          description: "Invalid project id"
